version: '3'

vars:
  DATE: '{{now | date "2006-01-02"}}'

tasks:
  deploy-srlinux:
    desc: Deploy the srlinux lab.
    dir: clab/srlinux
    cmds:
      - sudo containerlab deploy -t srl.clab.yml

  destroy-srlinux:
    desc: Destroy the srlinux lab.
    dir: clab/srlinux
    cmds:
      - sudo containerlab destroy -t srl.clab.yml --cleanup

  run-client:
    desc: Run the client.
    cmds:
      - go run cmd/client/main.go

  run-server:
    desc: Run the server.
    cmds:
      - go run cmd/server/main.go

  build-client:
    desc: |
      Build the client executable.
      Command format: task build-client -- [version].
    dir: cmd/client
    cmds:
      - |
        {{if .CLI_ARGS}}
          go build -ldflags "-X main.buildVersion={{.CLI_ARGS}} -X main.buildDate={{.DATE}}" -o client main.go
        {{else}}
          go build -ldflags "-X main.buildDate={{.DATE}}" -o client main.go
        {{end}}

  build-server:
    desc: |
      Build the server executable.
      Command format: task build-server -- [version].
    dir: cmd/server
    cmds:
      - |
        {{if .CLI_ARGS}}
          go build -ldflags "-X main.buildVersion={{.CLI_ARGS}} -X main.buildDate={{.DATE}}" -o server main.go
        {{else}}
          go build -ldflags "-X main.buildDate={{.DATE}}" -o server main.go
        {{end}}
