name: Static analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static:
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run static analysis
        run: |
          go vet ./...
