name: Static analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static:
    runs-on: ubuntu-latest
    container: golang:1.23
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          version: "latest"
          install-go: false
